
data01 = [ 1, 2, 2, 3, 3, 4, 5, 6 ];

mean_average = mean(data01, "a");
mean_average
mean_geometric = mean(data01, "g");
mean_geometric
mean_harmonic = mean(data01, "h");
mean_harmonic
mean_squared = meansq(data01);
mean_squared

quantile_0_1_min_max = quantile (data01, [0, 1]);   # Return minimum, maximum of distribution
quantile_0_1_min_max
quantile_025_05_075 = quantile (data01, [0.25 0.5 0.75]); # Return quartiles of distribution
quantile_025_05_075 = quantile (data01, [0.25 0.5 0.75]); # Return quartiles of distribution


percentile  = prctile (data01);
percentile

mmoment_1 = moment(data01, 1);
mmoment_1
mmoment_2 = moment(data01, 2);
mmoment_2
mmoment_3 = moment(data01, 3);
mmoment_3
mmoment_3_2 = moment(data01, 3.2);
mmoment_3_2
mmoment_5 = moment(data01, 5);
mmoment_5
mmoment_5_5 = moment(data01, 5.5);
mmoment_5_5

skewness = skewness(data01);
skewness

kurtosis = kurtosis(data01);
kurtosis 

# minimum, first quartile, median, third quartile, maximum, 
# mean, standard deviation, skewness, and kurtosis
statistics = statistics(data01);
statistics 

